links:
- note:
    el: Ιστοσελίδα Βουλής
    en: On Parliament
  url: http://www.parliament.cy/easyconsole.cfm/id/400
- note:
    el: Προσωπική ιστοσελίδα
    en: Personal website
  url: http://pprodromou.net/
- note:
    el: twitter
    en: twitter
  url: https://twitter.com/pprodromou
mugshot: http://www.parliament.cy/assets/image/imageoriginal/PRODROMOU%20Prodromos.jpg
name:
  el: Προδρόμου Πρόδρομος
  en: Prodromou Prodromos
tenures:
- district:
    el: Λευκωσία
    en: Lefkosia
  end_date: '2004-05-01'
  parl_group: ΔΗΣΥ
  start_date: '2001-06-07'
- district:
    el: Λευκωσία
    en: Lefkosia
  end_date: '2006-05-31'
  parl_group: null
  start_date: '2004-05-02'
- district:
    el: Λευκωσία
    en: Lefkosia
  end_date: null
  parl_group: ΔΗΣΥ
  start_date: '2013-03-07'
