name: Προδρόμου Πρόδρομος
summary: |
  Βουλευτής εκλογικής περιφέρειας Λευκωσίας του ΔΗΣΥ.
affiliation:
- start: '2001-06-07'
  end: '2004-05-01'   # inexact
  parl_group: ΔΗΣΥ
  district: Λευκωσία
- start: '2004-05-02'   # inexact
  end: '2006-05-31'
  parl_group:
  district: Λευκωσία
- start: '2013-03-07'
  end:
  parl_group: ΔΗΣΥ
  district: Λευκωσία
links:
- url: http://www.parliament.cy/easyconsole.cfm/id/400
  note: Ιστοσελίδα Βουλής
- url: http://pprodromou.net/
  note: Προσωπική ιστοσελίδα
- url: https://twitter.com/pprodromou
  note: twitter
mug: http://www.parliament.cy/assets/image/imageoriginal/PRODROMOU%20Prodromos.jpg
