name: Προδρόμου Πρόδρομος
summary: |
    Βουλευτής εκλογικής περιφέρειας Λευκωσίας του ΔΗΣΥ.
affiliation:
  - start: '2013-03-07'
    end:
    parl_group: ΔΗΣΥ
    district: Λευκωσία
links:
  - url: 'http://www.parliament.cy/easyconsole.cfm/id/400'
    note: Ιστοσελίδα Βουλής
mug: 'http://www.parliament.cy/assets/image/imageoriginal/PRODROMOU%20Prodromos.jpg'
