_sources:
- http://www.parliament.cy/easyconsole.cfm/id/400
birth_date: '1958-11-23'
dofi: null
email: pprodromou@parliament.cy
gender: male
identifiers:
- identifier: null
  scheme: http://www.wikidata.org/entity/
image: http://www.parliament.cy/assets/image/imageoriginal/PRODROMOU Prodromos.jpg
images:
- http://www.parliament.cy/assets/image/imageoriginal/PRODROMOU Prodromos.jpg
links:
- note:
    el: Προφίλ στην ιστοσελίδα της Βουλής
    en: Page on Parliament
    tr: null
  url: http://www.parliament.cy/easyconsole.cfm/id/400
- note:
    el: Προσωπική ιστοσελίδα
    en: Personal website
    tr: null
  url: http://pprodromou.net/
- note:
    el: twitter
    en: twitter
    tr: twitter
  url: https://twitter.com/pprodromou
name:
  el: Προδρόμου Πρόδρομος
  en: Prodromou Prodromos
  tr: Prodrómu Pródromos
other_names:
- name: Prodromou Prodromos
  note: Official spelling in the 'en' locale; possibly anglicised
- name: Prodromou Prodromos
  note: Official spelling in the 'el' locale; possibly anglicised
tenures:
- electoral_district:
    el: Λευκωσία
    en: Lefkosia
    tr: Lefkoşa
  end_date: '2004-05-01'
  parliamentary_group_id: disy
  start_date: '2001-06-07'
- electoral_district:
    el: Λευκωσία
    en: Lefkosia
    tr: Lefkoşa
  end_date: '2006-05-31'
  parliamentary_group_id: null
  start_date: '2004-05-02'
- electoral_district:
    el: Λευκωσία
    en: Lefkosia
    tr: Lefkoşa
  end_date: null
  parliamentary_group_id: disy
  start_date: '2013-03-07'
